apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  # namespace: cloudburst
  labels:
    app: cloudburst
spec:
  ttlSecondsAfterFinished: 3600  # Job will be cleaned up 1 hour after completion
  template:
    metadata:
      name: cloudburst
      labels:
        app: cloudburst
    spec:
      containers:
      - name: cloudburst
        image: "${CONTAINER_IMAGE}"
        imagePullPolicy: IfNotPresent
        env:
        - name: WORK_ITEM
          value: "${WORK_ITEM}"
        - name: STORAGE_TYPE
          value: "${STORAGE_TYPE}"
        - name: STORAGE_CONTAINER
          value: "${STORAGE_CONTAINER}"
        - name: STORAGE_PATH
          value: "${STORAGE_PATH}"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never  # OnFailure
      volumeMounts:
        - name: ssh-key
          mountPath: /root/.ssh/id_ed25519
          subPath: id_ed25519
          readOnly: true
        - name: ssh-known-hosts
          mountPath: /root/.ssh/known_hosts
          subPath: known_hosts
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
          defaultMode: 0400
      - name: ssh-known-hosts
        secret:
          secretName: ssh-known-hosts
          defaultMode: 0444
