apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  # namespace: cloudburst
  labels:
    app: cloudburst
spec:
  ttlSecondsAfterFinished: 3600  # Job will be cleaned up 1 hour after completion
  template:
    metadata:
      name: cloudburst
      labels:
        app: cloudburst
    spec:
      containers:
      - name: cloudburst
        image: "${CONTAINER_IMAGE}"
        imagePullPolicy: IfNotPresent
        env:
        - name: WORK_ITEM
          value: "${WORK_ITEM}"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never  # OnFailure
