services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"

  cloudburst-controller:
        build:
            context: .
            network: host
            platforms:
                - "linux/amd64"
#                - "linux/arm64"
#        shm_size: '1gb'
        image: bhdockr/cloudburst-controller
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
          - KUBECONFIG=/root/.kube/config
          - BROKER_URL=amqp://guest:guest@rabbitmq-service:5672
          - QUEUE=job1
          - CONTAINER_NAME=la-haz
          - CONTAINER_URL=bhdockr/la-haz:latest
        volumes:
          - ~/.kube/config:/root/.kube/config:ro
          - ./cloudburst-job-template.yaml:/app/cloudburst-job-template.yaml:ro
        depends_on:
          - rabbitmq
