apiVersion: v1
kind: Namespace
metadata:
  name: cloudburst
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudburst-controller
  namespace: cloudburst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudburst-controller
  template:
    metadata:
      labels:
        app: cloudburst-controller
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: cloudburst-controller
          image: us-west2-docker.pkg.dev/hip-field-293822/cloudburst-controller/cloudburst-controller
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"