apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudburst-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudburst-controller
  template:
    metadata:
      labels:
        app: cloudburst-controller
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: cloudburst-controller
          image: us-west2-docker.pkg.dev/hip-field-293822/cloudburst-service/cloudburst-controller
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
            - name: CONTAINER_NAME
              value: cloudburst1
            - name: CONTAINER_URL
              value: us-west2-docker.pkg.dev/hip-field-293822/cloudburst1/cloudburst1
            - name: AWS_REGION
              value: us-west-1
            - name: MODE_STR
              value: full
            - name: LOCAL_MODE
              value: '0'
            - name: MAX_CONCURRENT_JOBS
              value: '3'
