#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cloudburst
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudburst-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudburst-controller
  template:
    metadata:
      labels:
        app: cloudburst-controller
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: cloudburst-controller
          image: bhdockr/cloudburst-controller
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
            - name: METRICS_PORT
              value: "8000"
            - name: QUEUE_METRICS_INTERVAL_SECONDS
              value: "5"
          ports:
            - name: metrics
              containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: job-template
              mountPath: /app/cloudburst-job-template.yaml
              readOnly: true
      volumes:
        - name: job-template
          configMap:
            name: job-template
      restartPolicy: Never  # OnFailure