# kind-config.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 38617    # api server
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    certSANs:
      - bruce-mint
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30306  # mariadb
    hostPort: 30306       # Access via localhost:30306 from outside cluster
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 31672  # kubernetes
    hostPort: 31672       # Access via localhost:31672 from outside cluster
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 30900  # prometheus
    hostPort: 30900       # Access via localhost:30900 from outside cluster
    protocol: TCP
    listenAddress: "0.0.0.0"
    
