apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: cloudburst-controller
        metrics_path: /metrics
        static_configs:
          - targets:
              - cloudburst-controller-metrics.default.svc.cluster.local:8000
      - job_name: kube-state-metrics
        metrics_path: /metrics
        static_configs:
          - targets:
              - kube-state-metrics.default.svc.cluster.local:8080
