apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  selector:
    app: taskQueue
    component: rabbitmq
  type: NodePort
  ports:
  - appProtocol: amqp
    name: amqp
    port: 5672
    nodePort: 31672 # expose at amqp://guest:guest@localhost:31672
    protocol: TCP
  - appProtocol: http
    name: management
    port: 15672
    nodePort: 30672 # expose the mgmt ui at http://localhost:30672
    protocol: TCP
  - appProtocol: prometheus.io/metrics
    name: prometheus
    port: 15692
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        - name: management
          containerPort: 15672
          protocol: TCP
        - name: prometheus
          containerPort: 15692
          protocol: TCP
        resources:
          limits:
            cpu: 100m
