apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  selector:
    app: taskQueue
    component: rabbitmq
  type: NodePort
  ports:
  - appProtocol: amqp
    name: amqp
    port: 5672
    nodePort: 31672 # expose at amqp://guest:guest@localhost:31672
    protocol: TCP
  - appProtocol: http
    name: management
    port: 15672
    nodePort: 30672 # expose the mgmt ui at http://localhost:30672
    protocol: TCP
  - appProtocol: prometheus.io/metrics
    name: prometheus
    port: 15692
    protocol: TCP

