apiVersion: v1
kind: Pod
metadata:
  name: ssh-test
spec:
  containers:
    - name: ssh-container
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: ssh-key
          mountPath: /root/.ssh/id_ed25519
          subPath: id_ed25519
          readOnly: true
        - name: ssh-known-hosts
          mountPath: /root/.ssh/known_hosts
          subPath: known_hosts
          readOnly: true
  volumes:
    - name: ssh-key
      secret:
        secretName: ssh-key
        defaultMode: 0400
    - name: ssh-known-hosts
      secret:
        secretName: ssh-known-hosts
        defaultMode: 0444
