name: CI Docker Publish

on:
  push:
    branches:
      - main  # This will trigger the action when changes are pushed to the main branch.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx for caching and multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Cache Docker layers to speed up future builds
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 5: Build and push using Makefile (which invokes Docker Compose)
      - name: Build and push with Makefile
        run: make push